# permissions for end users to view bookservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bookserver-viewer-role
rules:
- apiGroups:
  - apiserver.example.com
  resources:
  - bookservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiserver.example.com
  resources:
  - bookservers/status
  verbs:
  - get
