# permissions for end users to edit bookservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bookserver-editor-role
rules:
- apiGroups:
  - apiserver.example.com
  resources:
  - bookservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiserver.example.com
  resources:
  - bookservers/status
  verbs:
  - get
